image: node:16

stages:
    - conventions
    - stylelint
    - eslint

commit_convention:
    stage: conventions
    needs: []
    cache:
        key: commitlint-node_modules
        paths:
            - node_modules/
    before_script:
        - bash -c "[[ -d node_modules/ ]] || npm install @commitlint/cli @commitlint/config-conventional; exit 0;"
    script:
        - npx --quiet commitlint --from="$CI_MERGE_REQUEST_DIFF_BASE_SHA" --help-url 'https://raccoongang.atlassian.net/wiki/spaces/PSC/pages/2662006787/RG+Delivery+Solutions+Conventional+Commits'
    rules:
        - if: "$CI_MERGE_REQUEST_EVENT_TYPE != 'merge_train' && $CI_MERGE_REQUEST_DIFF_BASE_SHA"

stylelint:
    stage: stylelint
    image: pipelinecomponents/stylelint:0.29.2
    before_script:
        - apk add git
        - git clone -b v14.15.0-rg1 https://github.com/raccoongang/frontend.git
        - npm i stylelint-config-standard-scss@v6.1.0
        - mv frontend/.stylelintrc .
    script:
        - npm run lint-style
    only:
        - merge_requests

eslint:
    stage: eslint
    before_script:
        - npm install
    script:
        - npm run lint-js
    only:
        - merge_requests
